### ISSUE TITLE
Explicit event registration for client

### ISSUE THREAD

**Issue by ihippocrate** [Invenietis/crs#7]
Currently, all of the crs dispatched events are sended to the crs-client throught the WebSocket connection, whihtout any filter.  
Problems : 

- No control on the data being sent to the client
- High bandwidth usage
- Can impact the client application performance

The crs-client **must**  subscribe on the desired events.

- [x] CRS must expose an endpoint to subscribe on an existing event, through HTTP or WS, for a given connection.
- [x] CRS must send an event to the client only if it has previously subscribed on it
- [ ] CRS must remove client subscriptions on connection loss
- [ ] to optimize the WS reconnection, CRS should allow the client to batch event subscriptions
- [ ] The CRS-client must also keep its subscriptions in order to send them back to the server during the reconnection phase

**Comment by clegendre** [comment]
Removed in the current version of CRS (2.0.0-alpha1).
